language: go

services:
    - docker

dist:
    - trusty

go:
    - "1.10"

before_install:
    - env | sort
    - sudo apt-get update
    - sudo apt-get -y install build-essential libglu1-mesa-dev libpulse-dev libglib2.0-dev

install:
    - go get -u -v github.com/therecipe/qt/cmd/...
    - go get github.com/360EntSecGroup-Skylar/excelize
    - go get -u github.com/gobuffalo/packr/...
    - go get github.com/tebeka/selenium

before_script:
    - mkdir driver
    - cd driver
    - wget https://chromedriver.storage.googleapis.com/2.38/chromedriver_linux64.zip
    - unzip chromedriver_linux64.zip
    - rm chromedriver_linux64.zip
    - mv chromedriver chromedriver_linux
    - wget https://chromedriver.storage.googleapis.com/2.38/chromedriver_win32.zip
    - unzip chromedriver_win32.zip
    - rm chromedriver_win32.zip
    - mv chromedriver.exe chromedriver_windows
    - cd ..
    - docker pull therecipe/qt:linux
    - docker pull therecipe/qt:windows_64_static

script:
    - packr -i linux.go
    - qtdeploy -docker -tags linux build linux
    - packr -i windows.go
    - qtdeploy -docker -tags windows build windows_64_static

after_script:
    - ls -alh deploy/linux
    - ls -alh deploy/windows
